name: Release

on:
  push:
    tags: [ "v*.*.*" ]    

env:
  REGISTRY_SERVER: registry.cennso.com

jobs:
  docker-build-push:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY_SERVER }}/${{ secrets.REGISTRY_PROJECT_NAME }}/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{raw}}
          flavor: |
            latest=false
            prefix=
            suffix=            
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
